In [2]:
import numpy as np
from seismostats.analysis.bvalue import BPositiveBValueEstimator, BMorePositiveBValueEstimator, UtsuBValueEstimator, ClassicBValueEstimator
from seismostats.analysis.bvalue.utils import shi_bolt_confidence

In [59]:
from seismostats.analysis.avalue import ClassicAValueEstimator, APositiveAValueEstimator, AMorePositiveAValueEstimator
from seismostats.analysis.bvalue import ClassicBValueEstimator, UtsuBValueEstimator, BMorePositiveBValueEstimator, BPositiveBValueEstimator


my_a_estimator = ClassicAValueEstimator()
my_apositive_estimator = APositiveAValueEstimator()
my_amorepositive_estimator = AMorePositiveAValueEstimator()

my_bclassic_estimator = ClassicBValueEstimator()
my_bmorepositive_estimator = BMorePositiveBValueEstimator()
my_bpositive_estimator = BPositiveBValueEstimator()
my_utsu_estimator = UtsuBValueEstimator()

my_magnitudes = [1.3, 0.6, 1. , 0.6, 1.1, 0.4, 3.5, 1.1, 0.7, 0.8, 1.1, 1.2, 1.6,
       0.5, 1.3, 1.5, 1.1, 0.8, 1.4, 2. , 1.1, 1. , 1.5, 1.3, 1.3, 0.9,
       1.4, 1.1, 1.6, 1.1, 1.1, 1. , 0.8, 0.8, 1.1, 0.7, 1.4, 2.4, 1.5,
       0.6, 0.3, 1.1, 1.1, 1.1, 1.1, 0.6, 1.3, 0.9, 1.6, 1.1, 1.3, 1.4,
       1.9, 1.3, 2.5, 1.9, 0.9, 0.9, 0.9, 1.2, 1.1, 0.7, 1.2, 1.2, 1.5,
       1.2, 1.3, 1.3, 0.9, 0.8, 1. , 1.7, 1.1, 2.3, 0.7, 1.2, 0.9, 1.3,
       1. , 0.6, 3.6, 1.3, 0.9, 0.9, 1.1, 1.2, 1.9, 0.3, 1.1, 1.2, 1.7,
       1.6, 2.3, 0.6, 1.6, 1.2, 1.6, 0.9, 0.8, 1.9, 1.4, 0.7, 0.5, 1. ,
       1.2, 0.8, 1.8, 1.1, 0.9, 0.8, 1.4, 1. , 1.4, 0.8, 2.2, 1.8, 0.9,
       1. , 0.7, 1.1, 1. , 1.1, 1.6, 1.3, 1.3, 3.1, 1. , 0.5, 1.1, 1.2,
       1.1, 1.8, 1.5, 2.1, 1.6, 1. , 1.8, 1.3, 1.5, 1.2, 0.8, 1.1, 1. ,
       1.1, 0.8, 0.5, 0.7, 1.1, 1.1, 1.7, 1.1, 1.5, 1.2, 2.9, 1.2, 0.7,
       1.3, 1.8, 1.1, 1.2, 1.4, 1. , 1.3, 1.5, 1. , 0.9, 0.8, 0.8, 1.5,
       0.6, 0.9, 1. , 1.4, 1.4, 1.7, 2.4, 1.6, 1.4, 1.8, 0.9, 1.2, 0.9,
       1. , 1. , 0.8, 0.9, 1.3, 1.1, 1.1, 1. , 0.7, 1.8, 1. , 1.6, 1. ,
       1.5, 1.6, 0.9, 0.8, 1.5, 0.9, 1. , 0.6, 1.5, 1.2, 0.3, 1.4, 1.4,
       1.1, 1.2, 1.4, 1.6, 1. , 0.7, 1.9, 1.2, 1.4, 1.3, 0.9, 1.1, 0.8,
       0.4, 2.2, 1.6, 1.9, 1.3, 1.2, 2.5, 1.1, 1.4, 2.7, 0.8, 1.3, 0.9,
       0.8, 1.1, 1.1, 1.6, 0.9, 0.7, 2.2, 2. , 2. , 0.6, 1.6, 1.6, 0.6,
       1.2, 2.5, 2. , 0.8, 0.9, 2.3, 1.5, 0.9, 0.4, 1. , 0.6, 1.3, 1.9,
       0.7, 1.1, 1.4, 1.6, 1.2, 1.2, 0.5, 1.7, 1.5, 1.3, 1.4, 1.5, 1.2,
       1.3, 1.2, 0.8, 0.9, 0.8, 0.6, 1.1, 1.1, 1.3, 1.5, 1.1, 1. , 1.7,
       0.6, 1.2, 0.7, 1.1, 1.5, 0.7, 1. , 0.9, 1.5, 1.1, 1.4, 1.6, 1.5,
       1.6]

mc = 2.0

my_a_value = my_a_estimator.calculate(my_magnitudes, mc, 0.1)
my_apositive_value = my_apositive_estimator.calculate(my_magnitudes, mc, 0.1, np.arange(len(my_magnitudes)))
my_amorepositive_value = my_amorepositive_estimator.calculate(my_magnitudes, mc, 0.1, np.arange(len(my_magnitudes)), 1.0)

my_b_value = my_bclassic_estimator.calculate(my_magnitudes, mc, 0.1)
my_bmorepositive_value = my_bmorepositive_estimator.calculate(my_magnitudes, mc, 0.1)
my_bpositive_value = my_bpositive_estimator.calculate(my_magnitudes, mc, 0.1)
my_utsu_value = my_utsu_estimator.calculate(my_magnitudes, mc, 0.1)

print(my_a_value, my_apositive_value, my_amorepositive_value)
print(my_b_value, my_bmorepositive_value, my_bpositive_value, my_utsu_value)

1.3222192947339193 1.390935107103379 1.472280706180855
0.8511027303988057 0.9409903567422798 0.9017663034908802 0.8483892204621659


In [61]:
my_a_estimator.magnitudes, my_apositive_estimator.magnitudes, my_amorepositive_estimator.magnitudes

(array([3.5, 2. , 2.4, 2.5, 2.3, 3.6, 2.3, 2.2, 3.1, 2.1, 2.9, 2.4, 2.2,
        2.5, 2.7, 2.2, 2. , 2. , 2.5, 2. , 2.3]),
 array([2.4, 2.5, 3.6, 3.1, 2.9, 2.5, 2.7, 2.5, 2.3]),
 array([3.6, 2.4, 2.5, 3.6, 3.6, 3.1, 3.1, 2.9, 2.5, 2.5, 2.7, 2.5, 2.5,
        2.5, 2.3]))

In [68]:
(1329 - 1052) / 439

0.6309794988610479

In [45]:
my_bclassic_estimator.magnitudes, my_bpositive_estimator.magnitudes, my_bmorepositive_estimator.magnitudes, my_utsu_estimator.magnitudes

(array([3.5, 2. , 2.4, 2.5, 2.3, 3.6, 2.3, 2.2, 3.1, 2.1, 2.9, 2.4, 2.2,
        2.5, 2.7, 2.2, 2. , 2. , 2.5, 2. , 2.3]),
 array([0.4, 0.1, 1.3, 0.9, 0.8, 0.3, 0.2, 0.5, 0.3]),
 array([0.1, 0.4, 0.1, 1.1, 1.3, 0.8, 0.9, 0.8, 0.1, 0.3, 0.2, 0.3, 0.5,
        0.5, 0.3]),
 array([3.5, 2. , 2.4, 2.5, 2.3, 3.6, 2.3, 2.2, 3.1, 2.1, 2.9, 2.4, 2.2,
        2.5, 2.7, 2.2, 2. , 2. , 2.5, 2. , 2.3]))

In [47]:
from seismostats.analysis.avalue import ClassicAValueEstimator, APositiveAValueEstimator, AMorePositiveAValueEstimator
from seismostats.analysis.bvalue import ClassicBValueEstimator, UtsuBValueEstimator, BMorePositiveBValueEstimator, BPositiveBValueEstimator

my_estimator = ClassicAValueEstimator()
my_apositive_estimator = APositiveAValueEstimator()
my_amorepositive_estimator = AMorePositiveAValueEstimator()

my_bclassic_estimator = ClassicBValueEstimator()
my_bmorepositive_estimator = BMorePositiveBValueEstimator()
my_bpositive_estimator = BPositiveBValueEstimator()
my_utsu_estimator = UtsuBValueEstimator()

my_magnitudes = [1.3, 0.6, 1. , 0.6, 1.1, 0.4, 3.5, 1.1, 0.7, 0.8, 1.1, 1.2, 1.6,
       0.5, 1.3, 1.5, 1.1, 0.8, 1.4, 2. , 1.1, 1. , 1.5, 1.3, 1.3, 0.9,
       1.4, 1.1, 1.6, 1.1, 1.1, 1. , 0.8, 0.8, 1.1, 0.7, 1.4, 2.4, 1.5,
       0.6, 0.3, 1.1, 1.1, 1.1, 1.1, 0.6, 1.3, 0.9, 1.6, 1.1, 1.3, 1.4,
       1.9, 1.3, 2.5, 1.9, 0.9, 0.9, 0.9, 1.2, 1.1, 0.7, 1.2, 1.2, 1.5,
       1.2, 1.3, 1.3, 0.9, 0.8, 1. , 1.7, 1.1, 2.3, 0.7, 1.2, 0.9, 1.3,
       1. , 0.6, 3.6, 1.3, 0.9, 0.9, 1.1, 1.2, 1.9, 0.3, 1.1, 1.2, 1.7,
       1.6, 2.3, 0.6, 1.6, 1.2, 1.6, 0.9, 0.8, 1.9, 1.4, 0.7, 0.5, 1. ,
       1.2, 0.8, 1.8, 1.1, 0.9, 0.8, 1.4, 1. , 1.4, 0.8, 2.2, 1.8, 0.9,
       1. , 0.7, 1.1, 1. , 1.1, 1.6, 1.3, 1.3, 3.1, 1. , 0.5, 1.1, 1.2,
       1.1, 1.8, 1.5, 2.1, 1.6, 1. , 1.8, 1.3, 1.5, 1.2, 0.8, 1.1, 1. ,
       1.1, 0.8, 0.5, 0.7, 1.1, 1.1, 1.7, 1.1, 1.5, 1.2, 2.9, 1.2, 0.7,
       1.3, 1.8, 1.1, 1.2, 1.4, 1. , 1.3, 1.5, 1. , 0.9, 0.8, 0.8, 1.5,
       0.6, 0.9, 1. , 1.4, 1.4, 1.7, 2.4, 1.6, 1.4, 1.8, 0.9, 1.2, 0.9,
       1. , 1. , 0.8, 0.9, 1.3, 1.1, 1.1, 1. , 0.7, 1.8, 1. , 1.6, 1. ,
       1.5, 1.6, 0.9, 0.8, 1.5, 0.9, 1. , 0.6, 1.5, 1.2, 0.3, 1.4, 1.4,
       1.1, 1.2, 1.4, 1.6, 1. , 0.7, 1.9, 1.2, 1.4, 1.3, 0.9, 1.1, 0.8,
       0.4, 2.2, 1.6, 1.9, 1.3, 1.2, 2.5, 1.1, 1.4, 2.7, 0.8, 1.3, 0.9,
       0.8, 1.1, 1.1, 1.6, 0.9, 0.7, 2.2, 2. , 2. , 0.6, 1.6, 1.6, 0.6,
       1.2, 2.5, 2. , 0.8, 0.9, 2.3, 1.5, 0.9, 0.4, 1. , 0.6, 1.3, 1.9,
       0.7, 1.1, 1.4, 1.6, 1.2, 1.2, 0.5, 1.7, 1.5, 1.3, 1.4, 1.5, 1.2,
       1.3, 1.2, 0.8, 0.9, 0.8, 0.6, 1.1, 1.1, 1.3, 1.5, 1.1, 1. , 1.7,
       0.6, 1.2, 0.7, 1.1, 1.5, 0.7, 1. , 0.9, 1.5, 1.1, 1.4, 1.6, 1.5,
       1.6]

my_a_value = my_estimator.calculate(my_magnitudes, 1.0, 0.1)
my_apositive_value = my_apositive_estimator.calculate(my_magnitudes, 1.0, 0.1)
my_amorepositive_value = my_amorepositive_estimator.calculate(my_magnitudes, 1.0, 0.1)

my_b_value = my_bclassic_estimator.calculate(my_magnitudes, 1.0, 0.1)
my_bmorepositive_value = my_bmorepositive_estimator.calculate(my_magnitudes, 1.0, 0.1)
my_bpositive_value = my_bpositive_estimator.calculate(my_magnitudes, 1.0, 0.1)
my_utsu_value = my_utsu_estimator.calculate(my_magnitudes, 1.0, 0.1)

print(my_a_value, my_b_value, my_bmorepositive_value, my_bpositive_value, my_utsu_value)

TypeError: APositiveAValueEstimator.calculate() missing 1 required positional argument: 'times'

In [3]:
estimator = BPositiveBValueEstimator(mc=2.0, delta_m=0.1)
bmp_estimator = BMorePositiveBValueEstimator(mc=2.0, delta_m=0.1)
utsu_estimator = UtsuBValueEstimator(mc=2.0, delta_m=0.1)
mags = np.array([2.0, 2.1, 2.1, 4.0, 5.0, 6.0, 2.0, 2.0])
weights = np.array([1, 1, 1, 2, 0.9, 0.2, 1, 0.8])
b_estimate = estimator(mags, weights=weights)
bmp_estimate = bmp_estimator(mags, weights=weights)
utsu_estimate = utsu_estimator(mags, weights=weights)
print(b_estimate, bmp_estimate, utsu_estimate)

0.37157318798757555 0.3119877038975013 0.4238327865393068


In [14]:
shi_bolt_confidence(mags, weights=2*np.ones(len(mags)), b=1.0)

0.9026211883417727

In [6]:
estimator = BMorePositiveBValueEstimator(mc=2.0, delta_m=0.1)
est = estimator(mags, weights=weights)
print(est, estimator.std)

0.3119877038975013 0.06789494811978714


/Users/leila/git_repos/github/SeismoStats/seismostats/analysis/bvalue/base.py:75: UserWarning: Shi and Bolt confidence with weights considers the magnitudes as having length 6.1000000000000005, the sum of relevant weights
  warnings.warn(


In [41]:
np.std(mags), np.sqrt(np.average(np.square(mags - np.average(mags, weights=weights)), weights=weights))

(1.49284753072777, 1.0944596825019437)

In [26]:
weights = np.ones(len(mags))
weights_extended = np.concatenate([weights, 0 * weights])
mags_extended = np.concatenate([mags, mags + 0.1])

est_ext = estimator(mags_extended, weights=weights_extended)
est = estimator(mags, weights)

In [27]:
est, est_ext

(0.45757490560675146, 0.45757490560675146)

In [ ]:
import numpy as np
from seismostats.analysis.avalue import estimate_a
magnitudes = np.array([2.1, 2.3, 2.0, 2.0, 2.1, 2.2, 2.1, 2.3])
mc = 2.0
delta_m = 0.1
m_ref = 3
b_value = 1
a = estimate_a(magnitudes, mc, delta_m, m_ref, b_value)
a